### ISSUE TITLE
NoSuchMethodError: setColorScheme

### ISSUE THREAD

**Issue by asleson** [raymondkam/Ti.SwipeRefreshLayout#13]
Hello,

I upgraded my Titanium build environment to Appcelerator Studio from Titanium Studio.  My app is now crashing with this error when it tries to show a screen that uses version 0.1 of `Ti.SwipeRefreshLayout`:

```
[ERROR] :  TiApplication: (main) [1398,1398] Sending event: exception on thread: main msg:java.lang.NoSuchMethodError: No virtual method setColorScheme(IIII)V in class Lcom/rkam/swiperefreshlayout/MySwipeRefreshLayout; or its super classes (declaration of 'com.rkam.swiperefreshlayout.MySwipeRefreshLayout' appears in /data/app/com.mywrightflyer-2/base.apk); Titanium 5.0.0,2015/09/15 23:07,ec79bc5
[ERROR] :  TiApplication: java.lang.NoSuchMethodError: No virtual method setColorScheme(IIII)V in class Lcom/rkam/swiperefreshlayout/MySwipeRefreshLayout; or its super classes (declaration of 'com.rkam.swiperefreshlayout.MySwipeRefreshLayout' appears in /data/app/com.mywrightflyer-2/base.apk)
[ERROR] :  TiApplication: 	at com.rkam.swiperefreshlayout.SwipeRefresh.processProperties(SwipeRefresh.java:67)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollProxy.setModelListener(KrollProxy.java:1209)

```
@raymondkam , any idea what's causing this and how I can fix it?  I'm dead in the water right now and it was working previously.

Thank you!!!

**Comment by zmcNotafraid** [comment]
setColorScheme() now deprecated
setColorSchemeResources(...color parameters) replace
