### ISSUE TITLE
App crash with searchView in the ActionBar or use of widget

### ISSUE THREAD

**Issue by timoa** [raymondkam/Ti.SwipeRefreshLayout#15]
Hi,

I use the widget nl.fokkezb.pullToRefresh with a dependency to your module for Android and all that find on a ListView with a searchView but if I add the searchView to the actionBar or if I use another widget like the nl.fokkezb.infiniteScroll, the app crash with this error:

```
[ERROR] InputEventReceiver: Exception dispatching input event.
[ERROR] E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
[ERROR] E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.widget.FrameLayout.getChildAt(int)' on a null object reference
[ERROR] E/MessageQueue-JNI: 	at com.rkam.swiperefreshlayout.MySwipeRefreshLayout.canChildScrollUp(MySwipeRefreshLayout.java:49)
[ERROR] E/MessageQueue-JNI: 	at com.rkam.swiperefreshlayout.SwipeRefreshLayout.onInterceptTouchEvent(SwipeRefreshLayout.java:640)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1960)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
[ERROR] E/MessageQueue-JNI: 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
[ERROR] E/MessageQueue-JNI: 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
[ERROR] E/MessageQueue-JNI: 	at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
[ERROR] E/MessageQueue-JNI: 	at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
[ERROR] E/MessageQueue-JNI: 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
[ERROR] E/MessageQueue-JNI: 	at android.view.View.dispatchPointerEvent(View.java:8666)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
[INFO]  JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5752)
[ERROR] E/MessageQueue-JNI: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5897)
[ERROR] E/MessageQueue-JNI: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
[ERROR] E/MessageQueue-JNI: 	at android.os.MessageQueue.nativePollOnce(Native Method)
[ERROR] E/MessageQueue-JNI: 	at android.os.MessageQueue.next(MessageQueue.java:143)
[ERROR] E/MessageQueue-JNI: 	at android.os.Looper.loop(Looper.java:122)
[ERROR] E/MessageQueue-JNI: 	at android.app.ActivityThread.main(ActivityThread.java:5254)
[ERROR] E/MessageQueue-JNI: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] E/MessageQueue-JNI: 	at java.lang.reflect.Method.invoke(Method.java:372)
[ERROR] E/MessageQueue-JNI: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
[ERROR] E/MessageQueue-JNI: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
[INFO]  Process: Sending signal. PID: 2037 SIG: 9
```

Any idea of what happen?

Thank you for your help!

Damien

**Comment by parnanzio** [comment]
I have the same problem 😞
