### ISSUE TITLE
V8Exception: Only the original thread that created a view hierarchy can touch its views.

### ISSUE THREAD

**Issue by suhailkaleem** [raymondkam/Ti.SwipeRefreshLayout#19]
i am using sdk 6.0.0 GA
with previous SDK it ran fine 
but now i get 

V8Exception: Only the original thread that created a view hierarchy can touch its views.

[WARN] :   W/System.err: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
[WARN] :   W/System.err: 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6629)
[WARN] :   W/System.err: 	at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:958)
[WARN] :   W/System.err: 	at android.view.ViewGroup.invalidateChild(ViewGroup.java:4707)
[WARN] :   W/System.err: 	at android.view.View.invalidateInternal(View.java:11882)
[WARN] :   W/System.err: 	at android.view.View.invalidate(View.java:11846)
[WARN] :   W/System.err: 	at android.view.View.invalidateParentIfNeeded(View.java:12035)
[WARN] :   W/System.err: 	at android.view.View.clearAnimation(View.java:17976)
[WARN] :   W/System.err: 	at android.support.v4.widget.SwipeRefreshLayout.startScaleDownAnimation(SwipeRefreshLayout.java:437)
[WARN] :   W/System.err: 	at android.support.v4.widget.SwipeRefreshLayout.setRefreshing(SwipeRefreshLayout.java:423)
[WARN] :   W/System.err: 	at android.support.v4.widget.SwipeRefreshLayout.setRefreshing(SwipeRefreshLayout.java:376)
[WARN] :   W/System.err: 	at com.rkam.swiperefreshlayout.SwipeRefresh.setRefreshing(SwipeRefresh.java:77)
[WARN] :   W/System.err: 	at com.rkam.swiperefreshlayout.SwipeRefreshProxy.setRefreshing(SwipeRefreshProxy.java:26)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:73)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1109)
[WARN] :   W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[WARN] :   W/System.err: 	at android.os.Looper.loop(Looper.java:135)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:118)

**Comment by DFoxinator** [comment]
@suhailkaleem did you ever figure anything out with this?

**Comment by jason-virak** [comment]
I also meet this problem. I used swiperefreshlayout V0.1 with scrollView Ti SDK V5.5.1. Could you help me on that?
